### ISSUE TITLE
.NET 版ライブラリの追加

### ISSUE THREAD

**Issue by codeyu** [holiday-jp/holiday_jp#108]
Hi, guys:
I made a .NET implementation for holiday_jp.
If you need I can transfer and maintain it.

https://github.com/codeyu/holiday_jp-csharp

**Comment by ne-sachirou** [comment]
👍 

どうでしょう? > @komagata @k1LoW

**Comment by k1LoW** [comment]
@codeyu GREAT!! AND WELCOME !!!

**Comment by codeyu** [comment]
OK. please add me as a member, thank you.

**Comment by codeyu** [comment]
done.

**Comment by k1LoW** [comment]
🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊 🎊
