### ISSUE TITLE
内閣府発行の syukujitsu.csv のファイル名が shukujitsu.csv に変更されている

### ISSUE THREAD

**Issue by Naba0123** [holiday-jp/holiday_jp#117]
突然 issue 建てすみません。
もし起票フローなどありましたら、ご教示いただければと思います。

タイトルの通りですが、今年の内閣府発行の祝日csvのパスが変更になり、合わせて test が失敗するようになっています。

fork で実行した結果
https://github.com/Naba0123/holiday_jp/actions/runs/4059631844

修正してみたところテストが通りましたので、プルリクを投げさせていただきます。

ref
* https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html
* https://blog.kenall.jp/entry/holidays-data-update-2023

**Comment by k1LoW** [comment]
ありがとうございます！！

**Comment by Naba0123** [comment]
内閣府が、リンク先を元に戻したそうです……
https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html

> 【2023年2月2日  リンク先URL訂正のお知らせ】
> 2023年2月1日付で更新した「昭和30年（1955年）から令和6年（2024年）国民の祝日」のCSVファイルの リンク先を従来のURLに訂正しました。
> 
> 訂正前  https://www8.cao.go.jp/chosei/shukujitsu/shukujitsu.csv
> 訂正後  https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv
> なお、掲載ファイルの内容については、変更ありません。

revert しますね。。

**Comment by k1LoW** [comment]
つらい...ありがとうございます
