### ISSUE TITLE
振替休日が何の日の振替なのかわからない

### ISSUE THREAD

**Issue by komagata** [holiday-jp/holiday_jp#45]
振替休日が全部**振替休日**という表記なので何の振替なのかわからない。

文化の日（振替休日）

のような表記にしたい。

**Comment by k1LoW** [comment]
テストに使っているGoogle Calendarだと `文化の日 振替休日` ですね。
`振替休日 (文化の日)` でも良さそうに思えるのがアレですね。

正式名称があればいいんですけど、調べた限りだと見つかりませんでした。

**Comment by komagata** [comment]
Google Calendarと同じ表記がいいですね。

**Comment by k1LoW** [comment]
良いと思います。ただ各言語ライブラリに影響があるので、タグ切ったほうが良い気がしますがいかがでしょう？

例えば

- 現行Ver: v0.9.0
- 振替休日名変更Ver: v1.0.0

みたいな感じで。メジャーバージョンが違ったほうが良さそう。

**Comment by komagata** [comment]
@k1LoW 

> タグ切ったほうが良い気がします

僕もそう思います。
