### ISSUE TITLE
Java 版のライブラリの追加

### ISSUE THREAD

**Issue by pine** [holiday-jp/holiday_jp#71]
holiday-jp の Java 版を開発したため、Organization 配下に追加させて頂いています。
何か問題点などあれば、ご指摘お願い致します 🙇 

https://github.com/holiday-jp/holiday_jp-java

**Comment by komagata** [comment]
おお、すばらしー！

**Comment by k1LoW** [comment]
最高です！！！

**Comment by pine** [comment]
特に無さそうなので、閉じますー。
