### ISSUE TITLE
Python 版ライブラリの追加

### ISSUE THREAD

**Issue by pine** [holiday-jp/holiday_jp#73]
無いので作ります。

**Comment by gabriel-tessier** [comment]
Hi,
We made a python version inspired from php and js version if you are ok I can transfer and help maintain.

https://github.com/LUXEYS/holiday_jp-python

m(_)m

**Comment by gabriel-tessier** [comment]
Sorry for the delay, but time to implement all the php features and check that we can stay up to date with the dataset you provide. 
Anyway now it's fine for us, if you accept to transfer the project. For sure we can continue to maintain and improve.

m(_)m

**Comment by gabriel-tessier** [comment]
どうでしょう? > @k1LoW

**Comment by k1LoW** [comment]
@gabriel-tessier すみません！見逃していました...！！ @gabriel-tessier さんを member に追加します！

**Comment by gabriel-tessier** [comment]
project transfer done!

@k1LoW  @pine

**Comment by k1LoW** [comment]
Welcome !!!!!
