### ISSUE TITLE
Elixir 版へのリンク追加 or organization へのお誘い

### ISSUE THREAD

**Issue by pine** [holiday-jp/holiday_jp#74]
既に存在されメンテナンスしていただけているようです。いかがでしょうか・・・？
https://github.com/ne-sachirou/holiday_jp-elixir

**Comment by k1LoW** [comment]
@pine 個人的には是非ご招待したいです！

**Comment by ne-sachirou** [comment]
すみません。怠けてこちらにお願いをしてをりませんでした。
参加させていただけないでしょうか。

**Comment by komagata** [comment]
@ne-sachirou さんをOrganizationへ追加しましたー。

**Comment by ne-sachirou** [comment]
移行しますm(_ _)m

**Comment by ne-sachirou** [comment]
しました。ありがとうございます
https://github.com/holiday-jp/holiday_jp-elixir

**Comment by ne-sachirou** [comment]
このissue閉じましょう…。(わたしには閉じる権限が無い)

**Comment by k1LoW** [comment]
よろしくお願いしますー
