### ISSUE TITLE
Go 版のライブラリの追加

### ISSUE THREAD

**Issue by pine** [holiday-jp/holiday_jp#75]
@komagata @k1LoW 

私の知り合いが holiday_jp の Go 言語版を移植してくれました。
organization 配下に移動 & メンバーに追加して頂くことは可能でしょうか?

https://github.com/ieee0824/holiday_jp-go

**Comment by komagata** [comment]
@pine ありがとうございます。@ieee0824 さんをorganizationのmemberに追加しましたー。

**Comment by pine** [comment]
ありがとうございます。本人に伝えますー。

**Comment by ieee0824** [comment]
追加ありがとうございます
早速リポジトリを移動します
