### ISSUE TITLE
holiday-jp/holiday_jp の v0.x と v1.x の違いと各ライブラリの対応状況についてまとめる

### ISSUE THREAD

**Issue by k1LoW** [holiday-jp/holiday_jp#77]
現在 #45 の対応により、以下のように振替休日における表記が異なっています。

| holiday-jp/holiday_jp Ver | 振替休日の表記 |
| --- | --- |
| v0.x | `振替休日` |
| v1.x | `勤労感謝の日 振替休日` |

上記への対応について、例えば https://github.com/holiday-jp/holiday_jp-php では

| holiday_jp-php Ver | holiday-jp/holiday_jp Ver |
| --- | --- |
| v1.x | v0.x |
| v2.x | v1.x |

としました。

ライブラリのバージョニング方針については各Ownerに任せるので良いかと思いますが、少なくともどのバージョンが holiday-jp/holiday_jp のどちらのメジャーバージョンに対応しているかは、まとめても良いかと考えています。

もし良ければ https://github.com/holiday-jp/holiday_jp/blob/master/README.md に記載しようかと。

いかがでしょう？

@komagata @pine @ne-sachirou

**Comment by komagata** [comment]
良いと思います。👍

**Comment by pine** [comment]
問題ないと思います 😃 
Swift 及び Java 版は、現状下記のようになっています。

|holiday_jp Ver|holiday_jp-swift Ver|holiday_jp-java Ver|
|--------------|--------------------|-------------------|
|v0.x                 |0.1.x                          |-                               |
|v1.x                  |0.2.x                         |0.1.x                         |
